<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net8.0</TargetFramework>
        <GeneratePackageOnBuild>true</GeneratePackageOnBuild>
        <PackageId>SignalRc</PackageId>
        <Version>1.0.0-beta</Version>
        <Authors>Daniel Berg</Authors>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <Description>Library for using SignalRC protocol</Description>
        <PackageLicenseExpression>MIT</PackageLicenseExpression>
    </PropertyGroup>

</Project>
